-- SQL files, will be executed at launch.
-- We need two users, one with rw right and another with just r right
-- Please julien create them
-- We need just one database : the Geoloc Database
-- After that you're free to create you're tables
--
--Dont forget to test the existence of the same users and database
